name = "adveny-potenziometro-brevo"
main = "index.ts"
compatibility_date = "2024-09-23"
workers_dev = true


# Variabili d'ambiente non sensibili
[vars]
SENDER_EMAIL = "info@adveny.it"
SENDER_NAME = "Adveny"
NOTIFY_EMAIL = "info@adveny.it"
BREVO_LIST_ID = "5"

# La chiave BREVO_API_KEY deve essere impostata come Secret protetto su Cloudflare:
# npx wrangler secret put BREVO_API_KEY
